const SandhedsDatabase = {
  kønList: [
    "Dreng",
    "Pige",
    "Ludderen",
    "Minecraft Mesa Biome",
    "Virksomhed",
    "Markeplejer",
    "Femboy",
    "Kønsneutral",
    "Hest"
  ],
  
  jobList: [
    "Netto",
    "Ridder",
    "Luder",
    "Fransk {køn}",
    "Arbejdsløs",
    "Gamer",
    "Pædagog",
    "Svindler",
    "Regøringsdame",
    "Cykelrytter",
    "Pornostjerne",
    "Steffen Brandt",
    "Kebab-mand",
    "Hestehandler",
    "Kontanthjælpsmodtager",
    "Youtuber",
    "Rapper",
    "Politiker",
    "Lærer",
    "Læge"
  ],
  
  raceList: [
    "God",
    "Underlegen",
    "Formula1",
    "Luddder",
    "Shrek",
    "Fed",
    "Mexico",
    "Normal",
    "Kartoffel",
    "Kina",
    "Alien"
  ],
  
  personlighedList: [
    "Emo",
    "Terrorist",
    "Lurder-{køn}",
    "Sigma",
    "Racist",
    "Idiot",
    "Ryan Gosling",
    "Selvglad",
    "Mystisk",
    "Macho",
    "Alkoholiker",
    "Feminist",
    "Kaotisk"
  ],
  
  sexOriList: [
    "Dyr",
    "Alt",
    "Børn",
    "Gay",
    "Stegepander",
    "Fiktive Kvinder",
    "Pixels",
    "Sig selv",
    "Mænd",
    "INTET",
    "Døde"
  ],
  
  turnOnOffList: [
    "Børn",
    "Store patter",
    "Rødbedesaft",
    "Fedme",
    "Prostituerede-{køn}",
    "Kage",
    "Reb",
    "Pikke",
    "Lugt",
    "Furry",
    "Smerte",
    "Blonde",
    "Interacial",
    "Ost",
    "Rugbrødsmadder",
    "Afføring",
    "Urin",
    "Blod",
    "Sæd",
    "Havenisse",
    "Frøer",
    "Risengrød",
    "Kesha",
    "Zanzibar",
    "Øl",
    "Sokker",
    "Matematik",
    "Heste",
    "Balloner"
  ],
  
  humørList: [
    "Luderisk",
    "Skattesvinder",
    "Glad",
    "Psykotisk",
    "Tissetrængende",
    "Loden",
    "Svært Deprimeret",
    "Liderlig",
    "Manisk",
    "Sulten",
    "Træt",
    "Sur",
    "Ked af det",
    "Rastløs",
    "Fornærmet",
    "Bange",
    "Håbløs",
    "Optimistisk",
    "Pessimistisk",
    "Forvirret",
    "Søvnig",
    "Seksuelt frustreret",
    "Fjollet",
    "Kreativ",
    "Inspireret",
    "Motiveret",
    "Overrasket",
    "Nysgerrig"
  ],
  
  karakterList: [
    "-3",
    "00",
    "02",
    "4",
    "7",
    "10",
    "12",
    "Istedgade",
    "Bundløs"
  ],
  
  økoList: [
    "Mange",
    "Fattig",
    "Middelklasse",
    "Luksusfælden",
    "Luderisk Økonomi",
    "Olie-Baron",
    "Eurojackpot rig",
    "Gældsslave",
    "Kviklån Geni"
  ],
  
  dyresteList: [
    "Cykel",
    "Chihuahua",
    "Toms Guldbar",
    "Guldbar",
    "Atlantisk Koloni",
    "Femboy Maid",
    "Mælkekarton",
    "NASA Computer",
    "PlayStation 3",
    "Godset",
    "Gammel pizza",
    "En sten",
    "40 Hektare Æbleplantage i Uganda",
    "2 Snes Guldmønter",
    "Et dusin tær"
  ],
  
  fremtidList: [
    "Død",
    "Rig",
    "Luder",
    "Kedelig",
    "Politiker",
    "Hjemløs",
    "Narkovrag",
    "Hjemløs og Narkovrag",
    "Atomfysiker",
    "Influencer",
    "Svensker",
    "Præsident af den demokratiske republik Zimbabwe",
    "Stuepige",
    "Aalborg Universitet Medialogi",
    "Klovn",
    "Fængsel"
  ],
  
  hårTypeList: [
    "Krøllet",
    "Glat",
    "Fedtet",
    "Langt",
    "Kort",
    "Grimt",
    "Afro",
    "Luder",
    "Henningen",
    "Tagrenden",
    "Boosie Fade",
    "Flettet"
  ],
  
  stilList: [
    "Dårlig",
    "Luder",
    "Emo",
    "Gammel",
    "Bøsset",
    "Nøgen",
    "Elegant",
    "Cowboy",
    "Lærer",
    "Fursuit",
    "Elgiganten",
    "Goth",
    "Hjemløs",
    "Bimbo"
  ],
  
  højdeList: [
    "Dværg",
    "Gnom",
    "Rundetårn",
    "Havenisse",
    "Basketball",
    "40.000.000 m",
    "Giraf",
    "Christianit",
    "Langt Højere Bjærge",
    "Uendelig",
    "23 Skrupel",
  ],
  
  vægtList: [
    "Usund",
    "Overvægtig",
    "Femboy",
    "Skelet",
    "Fed",
    "Gamer",
    "Helt normal",
    "Hest",
    "XXX-Large",
    "Underernæret",
    "Tynd",
    "4 Unse",
    "3,4 Centner"
  ],
  
  religionList: [
    "Heden",
    "Luder",
    "Flyvende Spaghetti Monster",
    "Borbon",
    "Spronk",
    "Jøde",
    "Kristen",
    "Buddhist",
    "MAGA",
    "Mortisme",
    "Satanisme",
    "Ateist",
    "Muslim",
    "Scientology",
    "Hindu"
  ],

  musiksmagList: [
    "Pop",
    "Rock",
    "Metal",
    "Jazz",
    "Klassisk",
    "Country",
    "Hip-Hop",
    "Elektronisk",
    "Folk",
    "Reggae",
    "Luder Musik",
    "K-pop",
    "Indie",
    "Punk",
    "Disco",
    "Heavy Metal",
    "Videospil Musik",
    "Rap",
    "Rape",
    "{race} Hip-Hop",
    "{race}-pop",
    "{race} Rap",
    "Støj",
    "Opera",
    "Funk",
    "Blues"
  ],

  strList: [
    "9000+",
    "Moskusokse",
    "Bodybuilder",
    "Luder",
    "Hulk",
    "Wrestler",
    "Baby"
  ],
  
  dexList: [
    "Rumæner",
    "Polak",
    "Cyklende",
    "Meget Højt Hus",
    "Ninja",
    "Klodset"
  ],
  
  conList: [
    "Elefant",
    "Stenmur",
    "Dinosaurus",
    "Gummibåd",
    "Betonsøjle",
    "Pap",
    "Rustfri stål",
    "Nokia"
  ],
  
  intList: [
    "Klog rotter",
    "Autostol",
    "OBH Nordica Stavblender",
    "Venstre håndet",
    "WikiPedia",
    "Kompetent",
    "Intelligent",
    "Gennemsnitlig",
    "Dum",
    "Hjerneskadet",
    "Negativ IQ"
  ],
  
  wisList: [
    "Troldmand",
    "Kinesisk",
    "Undervands gris",
    "Gådefuld",
    "Kosmisk",
    "Glemsom",
    "Orakel"
  ],
  
  chaList: [
    "-999",
    "Rizzler",
    "Sexy",
    "Ikke sej",
    "Skibidi Rizz",
    "Kedelig",
    "Egendomsmægler"
  ],
  
  perkList: [
    "Mega diller",
    "Farveblind",
    "Diarré",
    "Kannibal",
    "Alkoholiker",
    "Sexy",
    "Ludoman",
    "{køn} AIDS",
    "æbel tært",
    "PERK50",
    "Autisme",
    "Svedig",
    "Nærig",
    "Doven",
    "Uendelig Sæd"
  ],

  fornavnList: [
    "Lars",
    "Mikkel",
    "Søren",
    "Anders",
    "Peter",
    "Jens",
    "Thomas",
    "Michael",
    "Christian",
    "Kasper",
    "Rasmus",
    "Mathias",
    "Frederik",
    "Emil",
    "Oliver",
    "Mads",
    "Niels",
    "Johnny",
    "John",
    "Mogens",
    "Lone",
    "Anne",
    "Maria",
    "Elon",
    "Kurt",
    "Poul",
    "Hans",
    "Ole",
    "Jørgen",
    "Donald",
    "Mette",
    "Jack",
    "Kong",
    "Johan",
    "Simon",
    "Torkild",
    "Yrotmer",
    "Svend",
    "Bo",
    "Rolf",
    "Reqonmi",
    "Mort",
    "Pikmer",
    "Kürt",
    "Síf",
    "Jeppé",
    "Ægir",
    "Håkon",
    "Sylte",
    "Ludvig",
    "Boris"
  ],

  mellemnavnList: [
    "Andersen",
    "Jensen",
    "Nielsen",
    "Hansen",
    "Pedersen",
    "Christensen",
    "Larsen",
    "Madsen",
    "Olsen",
    "Rasmussen",
    "Henning",
    "Fede",
    "Thomas",
    "Bo",
    "Rust",
    "Igiliflimut",
    "Fisseprut",
    "Piromera",
    "Von Luderstein"
  ],

  efternavnList: [
    "Jensen",
    "Nielsen",
    "Hansen",
    "Pedersen",
    "Andersen",
    "Christensen",
    "Larsen",
    "Madsen",
    "Olsen",
    "Rasmussen",
    "Musk",
    "Trump",
    "Smith",
    "Johnson",
    "Dahl",
    "Ko",
    "Mikkelsen",
    "Ford",
    "Fod",
    "Regnys",
    "Metramotiv",
    "Fiminit",
    "Luder",
    "Stegosaurus",
    "Urinitis",
    "Xylomispis",
    "Johnson",
    "Rigcardtos",
    "Karlen"
  ]
};